---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schemas.qloo.solo.io
spec:
  group: qloo.solo.io
  names:
    kind: Schema
    listKind: SchemaList
    plural: schemas
    singular: schema
  scope: Namespaced
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: resolvermaps.qloo.solo.io
spec:
  group: qloo.solo.io
  names:
    kind: ResolverMap
    listKind: ResolverMapList
    plural: resolvermaps
    singular: resolvermap
  scope: Namespaced
  version: v1

---
#rbac for function-discovery
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qloo-role
rules:
- apiGroups: ["qloo.solo.io"]
  resources: ["schemas", "resolvermaps"]
  verbs: ["*"]
- apiGroups: ["gloo.solo.io"]
  resources: ["virtualservices"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qloo-cluster-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: gloo-system
roleRef:
  kind: ClusterRole
  name: qloo-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: qloo
  namespace: gloo-system
  labels:
    gloo: qloo
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: qloo
  template:
    metadata:
      labels:
        gloo: qloo
    spec:
      initContainers:
      - name: assignnodeid
        image: busybox
        command:
        - sed
        - s/NODE_ID_PLACE_HOLDER/$(POD_NAME).$(POD_NAMESPACE)/;w /config-tmp/envoy.yaml
        - "/config/envoy.yaml"
        volumeMounts:
        - name: qloo-proxy-config
          mountPath: /config
        - name: config-tmp
          mountPath: /config-tmp
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      containers:
      - name: proxy
        image: "soloio/envoy:0.2.27"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        - containerPort: 19000
          name: admin
        command: ["envoy"]
        args: ["-c", "/config/envoy.yaml", "--v2-config-only"]
        volumeMounts:
        - name: config-tmp
          mountPath: /config
      - name: qloo
        image: "soloio/qloo:0.1.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
          name: http
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=1m"
        - "--kube.namespace=gloo-system"
        volumeMounts:
        - name: config-tmp
          mountPath: /config
      volumes:
      - name: qloo-proxy-config
        configMap:
          name: qloo-proxy-config
      - name: config-tmp
        emptyDir: {}
---
# GW
apiVersion: v1
kind: Service
metadata:
  name: qloo
  namespace: gloo-system
  labels:
    gloo: qloo
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      protocol: TCP
      name: http
  selector:
    gloo: qloo


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: qloo-proxy-config
  namespace: gloo-system
data:
  envoy.yaml: |
    node:
      cluster: qloo
      id: qloo~NODE_ID_PLACE_HOLDER
    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 5.000s
        hosts:
        - socket_address:
            address: control-plane
            port_value: 8081
        http2_protocol_options: {}
        type: STRICT_DNS
    dynamic_resources:
      ads_config:
        api_type: GRPC
        grpc_services:
        - envoy_grpc: {cluster_name: xds_cluster}
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 19000


### Gloo

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: upstreams.gloo.solo.io
spec:
  group: gloo.solo.io
  names:
    kind: Upstream
    listKind: UpstreamList
    plural: upstreams
    singular: upstream
  scope: Namespaced
  version: v1

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualservices.gloo.solo.io
spec:
  group: gloo.solo.io
  names:
    kind: VirtualService
    listKind: VirtualServiceList
    plural: virtualservices
    singular: virtualservice
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: roles.gloo.solo.io
spec:
  group: gloo.solo.io
  names:
    kind: Role
    listKind: RoleList
    plural: roles
    singular: role
  scope: Namespaced
  version: v1

---
# Source: gloo/templates/rbac.yaml
---
#rbac for control-plane
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "secrets", "endpoints", "configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "create"]
- apiGroups: ["gloo.solo.io"]
  resources: ["upstreams", "virtualservices", "roles"]
  verbs: ["*"]
---
#rbac for function-discovery
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-discovery-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["gloo.solo.io"]
  resources: ["upstreams", "virtualservices"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: gloo-system
roleRef:
  kind: ClusterRole
  name: gloo-role
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-discovery-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: gloo-system
roleRef:
  kind: ClusterRole
  name: gloo-discovery-role
  apiGroup: rbac.authorization.k8s.io

---
# Source: gloo/templates/control-plane.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: control-plane
  namespace: gloo-system
  labels:
    gloo: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: control-plane
  template:
    metadata:
      labels:
        gloo: control-plane
    spec:
      containers:
      - name: control-plane
        image: "soloio/control-plane:0.3.0"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=1m"
        - "--secrets.type=kube"
        - "--secrets.refreshrate=1m"
        - "--files.type=kube"
        - "--files.refreshrate=1m"
        - "--xds.port=8081"
        - "--kube.namespace=gloo-system"
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane
  namespace: gloo-system
  labels:
    gloo: control-plane
spec:
  ports:
    - port: 8081
      protocol: TCP
      name: http
  selector:
    gloo: control-plane
---
# Source: gloo/templates/function-discovery.yaml

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: function-discovery
  namespace: gloo-system
  labels:
    gloo: function-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      gloo: function-discovery
  template:
    metadata:
      labels:
        gloo: function-discovery
    spec:
      containers:
      - name: function-discovery
        image: "soloio/function-discovery:0.3.0"
        imagePullPolicy: IfNotPresent
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=30m"
        - "--secrets.type=kube"
        - "--secrets.refreshrate=30m"
        - "--files.type=kube"
        - "--files.refreshrate=30m"
        - "--kube.namespace=gloo-system"

---
# Source: gloo/templates/upstream-discovery.yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: upstream-discovery
  name: upstream-discovery
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: upstream-discovery
  replicas: 1
  template:
    metadata:
      labels:
        gloo: upstream-discovery
    spec:
      containers:
      - image: soloio/upstream-discovery:0.3.0
        imagePullPolicy: IfNotPresent
        name: upstream-discovery
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=30m"
        - "--kube.namespace=gloo-system"
