steps:

  - name: 'gcr.io/cloud-builders/wget'
    entrypoint: ./ci/spell.sh
    args: ['check']
    waitFor: ['-']
    env:
      - 'LSCOMMAND=find * -path gopath -prune -o -print'
    id: 'check-spelling'
  # Can create a dep cache by running 'gcloud builds submit . --config=cloudbuild-cache.yaml'
  # These two steps should populate the cache
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args: ['-c', 'mkdir -p ./gopath/pkg/dep && gsutil cat gs://solo-public-cache/sqoop/sqoop-dep.tar.gz | tar -xzf -']
    id: 'download-untar-dep-cache'
    waitFor: ['-']

  # Run dep to set up the project so it can be built and tested
  # Dep modifies workspace so that the code is moved into the PROJECT_ROOT
  # All steps after this must set GOPATH
  - name: 'gcr.io/$PROJECT_ID/dep'
    args: ['ensure']
    env:
      - 'PROJECT_ROOT=github.com/solo-io/sqoop'
      - 'GIT_SSH_CONFIG=FALSE'
    id: 'dep'