site_name: Sqoop
pages:
    - Index: index.md
    - Introduction:
      - Introduction: introduction/introduction.md
      - Concepts:
         - API Objects: introduction/concepts/api_objects.md
         - Resolvers: introduction/concepts/resolvers.md
      - Architecture: introduction/architecture.md
    - Installation:
      - Installing on Docker: installation/docker.md
      - Installing on Kubernetes: installation/kubernetes.md
    - Getting Started:
#      - Docker:
#        - Basic Routing: getting_started/docker/1.md
#        - Function Routing: getting_started/docker/2.md
      - Docker: getting_started/docker/1.md
      - Kubernetes: getting_started/kubernetes/1.md
#      - AWS:
#        - Basic Lambda with Gloo: getting_started/aws/lambda.md
#    - Dev Guide: dev/README.md
#    - Tutorials:
#    - Advanced:
#      - Bootstrap Options: advanced/bootstrap_options.md
    - v1 API reference:
      - Schemas: v1/schema.md
      - ResolverMaps: v1/resolver_map.md
      - Config: v1/config.md
repo_url: https://github.com/solo-io/sqoop/
site_author: gloo Project Authors
copyright: © Copyright 2018, solo.io Inc.
google_analytics: ['UA-101654320-1', 'sqoop.solo.io']
theme:
  name: 'mkdocs'
  favicon: 'img/favicon.ico'
extra_css: [extra.css]
extra:
    version: 0.1.1
