########################################################################
###                                                                  ###
###                        Sqoop                                     ###
###                                                                  ###
########################################################################


sqoop:
  deployment:
    name: sqoop
    image:
      tag: v1
      repository: soloio/sqoop
      pullPolicy: Always
  service:
    port: 9000
