{{ if .Values.metrics.status -}}
{{ if eq .Values.metrics.status "prometheus" "all" -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "statsd.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statsd
  template:
    metadata:
      name: {{ template "statsd.name" . }}
      namespace: {{ .Release.Namespace }}
      labels:
        app: statsd
    spec:
      containers:
      - name: statsd
        image: {{ .Values.metrics.statsd_exporter }}
        ports:
        - name: web
          containerPort: 9102
        - name: statsd
          containerPort: 9125
        livenessProbe:
          httpGet:
            path: /metrics
            port: 9102
          initialDelaySeconds: 15
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    name: statsd
    app: statsd
  name: {{ template "statsd.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: statsd
  ports:
  - name: web
    protocol: TCP
    port: 9102
  - name: statsd
    protocol: TCP
    port: 9125
{{ end -}}
{{ end -}}